### ISSUE TITLE
image demage

### ISSUE THREAD

**Issue by CHOJUIL** [Gregwar/Image#106]
Image::open($imgPath)
		 ->zoomCrop(120, 160, 'transparent', 'center', 'center')
		 ->negate()
		 ->save($thumbPath);

before

![a](https://cloud.githubusercontent.com/assets/16010967/11388763/eb237ba6-937c-11e5-8eb8-e697f94ff679.jpg)

after

![5652ed0dea608_s](https://cloud.githubusercontent.com/assets/16010967/11388765/ee840afe-937c-11e5-8b35-fe874cce0c58.jpg)

**Comment by Soullivaneuh** [comment]
Well, what is the problem?

**Comment by CHOJUIL** [comment]
color demaged

**Comment by Soullivaneuh** [comment]
You are using `->negate()` on your code. This is the expected color result of this method.
