### ISSUE TITLE
maxDimensionsResize

### ISSUE THREAD

**Issue by garygreen** [Gregwar/Image#107]
Is there currently a way to only scale resize if either the width or height is larger than X?

This is useful if you want users to upload any size image but scale down on the server if too large.

something like:

```php
$image->maxDimensionsResize([2048, 2048]); // Image is 1024, 800 and won't be touched.
$image->maxDimensionsResize([2048, 2048]); // Image is 3000, 800 and will scale down
```

**Comment by Soullivaneuh** [comment]
I would say this belong more to code logic that the library itself.

```php
if ($width > 2048) {
    resize(...)
}
```

**Comment by garygreen** [comment]
Maybe. But I think it's common enough to warrant being a proper resize method.

Maybe `scaleDownResize()`

**Comment by Soullivaneuh** [comment]
@Gregwar What do you think?

**Comment by Gregwar** [comment]
Actually, `cropResize()` already does this since it will not downscale and crops the extra padding
(Really late reply warning, don't know if it's usefull)
