### ISSUE TITLE
Do this module have an watermark functionality

### ISSUE THREAD

**Issue by pyatnitsev** [Gregwar/Image#128]
Hello!

I need to add watermarks for all my images, that crop by this library (I'm using Symfony Bundle).
Is there any way to do it?

**Comment by Syndesi** [comment]
Meanwhile there was an update to merge two images into a single one.
The watermark-example can be found [here](https://github.com/Gregwar/Image/blob/master/demo/watermark.php).

**Comment by pyatnitsev** [comment]
Thanks!
