### ISSUE TITLE
Not all methods are listed

### ISSUE THREAD

**Issue by piernik** [Gregwar/Image#132]
I'm using PhpStorm IDE.
Not all methods are listed in Image class comment eg.: resize.
It's not recognized by IDE.

**Comment by Gregwar** [comment]
Would you mind making a PR for that?

**Comment by piernik** [comment]
There no need for PR. Here are screenshots.
`resize` is marked because IDE don't know what is it.

![image1](https://cloud.githubusercontent.com/assets/420691/20707689/b06ab8de-b62c-11e6-8473-75e418c7de4f.png)

`resize` is not listed here.

![image2](https://cloud.githubusercontent.com/assets/420691/20707695/b433e9cc-b62c-11e6-9b84-364637cc9751.png)
