### ISSUE TITLE
Fatal error: Class 'Gregwar\Image\Image' not found in

### ISSUE THREAD

**Issue by tomkochi** [Gregwar/Image#146]
I am new to use composer. when i use image resize svcript it gives the error:
Fatal error: Class 'Gregwar\Image\Image' not found in index.php on line 3

index.php:
<?php use Gregwar\Image\Image;

Image::open('in.jpg')
     ->resize(100, 100)
     ->negate()
     ->save('out.jpg');

**Comment by Gregwar** [comment]
How did you installed the library?

Use:

```
composer req gregwar/image
```

And then include the `vendor/autoload.php` file generated by composer in your code

**Comment by tomkochi** [comment]
Thanks a lot, dear.

Actually, I missed to include the autoload.php

Anyway, it's great work! I love your plugin. Its superb.

Now I am up to searching if you have more plugins... I am sure there will
be.

Fantastic work!

**Comment by Gregwar** [comment]
`packagist.org` will be the place you want then ;-)
