### ISSUE TITLE
Deprecation error on Symfony 4.2 and up

### ISSUE THREAD

**Issue by Thorry84** [Gregwar/Image#157]
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

Maybe something to look at? I've seen a lot of packages have this problem.

**Comment by aweelex** [comment]
@Thorry84 Please comment. Where have you seen usage of TreeBuilder?

**Comment by Thorry84** [comment]
@aweelex Oops, just noticed I posted this in Gregwar/Image, but it was meant to be posted in the Gregwar/ImageBundle. My bad!

The reference is here: https://github.com/Gregwar/ImageBundle/blob/0024f16805cc3cf123ae4ac70ade1dd39eccc103/DependencyInjection/Configuration.php#L18
