### ISSUE TITLE
Class Gregwar\Image\Adapter\Imagick contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by oojacoboo** [Gregwar/Image#167]
>Class Gregwar\Image\Adapter\Imagick contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Gregwar\Image\Adapter\AdapterInterface::saveWebp)

**Comment by doxt3r** [comment]
You need to install imagick php extension and also imagemagick package in your system to fix this issue.
source: https://stoorm.org/article/probleme-class-gregwarimageadapterimagick-contains-1-abstract-method-and-must-therefore-be-declared-abstract-or-implement-the-remaining-methods

**Comment by oojacoboo** [comment]
@doxt3r AKAIK this issue was already resolved.  I don't see how your suggestion makes sense as a resolution for this namespaced lib.  Anyway, closing this out.
