### ISSUE TITLE
copy(cache/images/f/a/l/l/b/fallback.jpg): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by hebertlima** [Gregwar/Image#174]
Hey friend!
first of all, thank you! this library is amazing!

Everything works fine on localhost, but I've got this error on AWS host,
I gave permission 775 for this file:  `vendor/gregwar/image/Gregwar/Image/Image.php` but still not working, 
may you help?

```js
"message": "copy(cache/images/f/a/l/l/b/fallback.jpg): failed to open stream: No such file or directory",
"exception": "ErrorException",
"file": "/var/www/html/project/vendor/gregwar/image/Gregwar/Image/Image.php",
```

**Comment by basteyy** [comment]
Is the folder valid? 

What is the output of the following
```
<?php
var_dump(is_dir('cache/images/f/a/l/l/b/'))

```

**Comment by hebertlima** [comment]
the problem was the server without the lib to create jpeg images
