### ISSUE TITLE
Error during generate non-existing file

### ISSUE THREAD

**Issue by piotrchludzinski** [Gregwar/Image#2]
This is part of my template.

{{ image('image_uploads/' ~ program.id ~ '.jpg').resize(118,88) }}

When file don't exist occurs error.

<img src="/
Fatal error: Method Gregwar\ImageBundle\ImageHandler::__toString() must not throw an exception in /home/pchludzinski/www/d3/Symfony/app/cache/dev/classes.php on line 7063

**Comment by TrkiSF2** [comment]
@Gregwar any news about broken jpgs? I think I just run into issue like that but I am not sure.

The problem is that the response is 503 and there is no error log what so ever in symfony, apache logs. Result is a completely white page.

When I switch the environment to dev I see at least this error:

    [2015-02-25 14:10:02] scream.WARNING: unlink(/var/www/deploys/.com/prod/releases/20150217214148/app/../web/cached_images/3/8/d/3/5/38d35c6935221b7765b7eeda0f2b739b84d04edc.png): No such file or directory {"type":2,"file":"/var/www/deploys/.com/prod/shared/vendor/gregwar/cache/Gregwar/Cache/Cache.php","line":270,"scream":0} []

I will add more details in this afternoon.

**Comment by TrkiSF2** [comment]
Found a problem. From some reason I am not able to resize this image and it ends up in a fatal crush of the whole request:
![54ed49c714f7d](https://cloud.githubusercontent.com/assets/3595242/6378248/5540322e-bd2a-11e4-983b-07e65ac91093.png)

The image description suits the problem :(

**Comment by TrkiSF2** [comment]
On the local the script runs without problems which means the size of 712kB is too much as it's a transparent image for the server. 

What's the best solution now?

1. increase some (which?) settings to handle it
2. prevent transparent big .png? 

Hmm let me please know asap @Gregwar 

Thank you

**Comment by Adambean** [comment]
Out of interest, was the "throw_exception" configuration option expanded to work with toString()? I've set this configuration property to false and supplied a fallback image, but still get an exception if an image couldn't be found.

> Error: Method Gregwar\ImageBundle\ImageHandler::__toString() must not throw an exception, caught Error: Call to a member function log() on null
