### ISSUE TITLE
Combine multiple images / Sprite

### ISSUE THREAD

**Issue by garygreen** [Gregwar/Image#72]
Is this possible? For instance, creating a sprite from multiple images to save on HTTP requests.

**Comment by Gregwar** [comment]
I don't understand what you want to do
Maybe you're talking of merge ()?

**Comment by garygreen** [comment]
For instance like https://github.com/Ensighten/grunt-spritesmith

Interesting, I didn't see `merge` before. It's not quite what I'm after as with this it seems you need to pass x, y, width, height, i was looking for more an automatic method for combing multiple images maybe one on-top of another. Have you seen the [CSS Sprite technique](http://www.smashingmagazine.com/2009/04/27/the-mystery-of-css-sprites-techniques-tools-and-tutorials/)? That's primary reason for wanting this

**Comment by garygreen** [comment]
I supose thinking about it you would need a way of generating a CSS file as well with the x, y start coordinates for the merged/combined images, or at least a dedicated method that will return a keyed-filename array with the coordinates like:

```php
$coordinates = Gregwar::createSprite('file1.jpg', 'file2.jpg');

'file1.jpg' => [0, 0],
'file2.jpg' => [0, 300]
```

Probably outside scope of this package itself though.

**Comment by Gregwar** [comment]
Indeed, but it's not a really hard problem though

I think there is already scripts to do this specifically
