### ISSUE TITLE
GITHUB_OAUTH_TOKEN

### ISSUE THREAD

**Issue by Soullivaneuh** [Gregwar/Image#89]
@Gregwar Could you please set up the GITHUB_OAUTH_TOKEN private variable? No special authorizations needed, just used for auth.

Related to #88.

**Comment by Gregwar** [comment]
Can you enlight me on that one?
What is the goal of this token?

**Comment by Soullivaneuh** [comment]
This token will permit authentication against GitHub to avoid api download limit.

**Comment by Gregwar** [comment]
Ok, I set GITHUB_OAUTH_TOKEN in the repo environment variables for Travis

**Comment by Gregwar** [comment]
Actually, maybe I'm a little paranoid, but I don't think this really secure to do

**Comment by Gregwar** [comment]
What will happen if someone fork the repository, and change this:

```
before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
```

To this:

```
before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - echo $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit --no-update
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
```

And then make a pull request?

**Comment by Soullivaneuh** [comment]
@Gregwar I'm surprised that you didn't ask the question earlier.

Absolutely nothing, private token are not set on PR Travis jobs. :-)
